# Generated by Django 6.0.7 on 2026-07-15 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='category',
        ),
    ]
