# Generated by Django 6.0.7 on 2026-08-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_product_unique_product_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
