# Generated by Django 6.0.7 on 2026-08-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='investment_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
