# Generated by Django 6.0.7 on 2026-08-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_product_investment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
