# Generated by Django 6.0.7 on 2026-07-13 04:14

from django.db import migrations


def rename_categories(apps, schema_editor):
    Category = apps.get_model("finances", "Category")

    Category.objects.filter(name="Transport").update(name="Transporte")


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_rename-categories'),
    ]

    operations = [
        migrations.RunPython(rename_categories),
    ]
